version: 2.1


jobs:
  my_job:
    docker:
      - image: circleci/node:13.8.0
    steps:
       - run: echo 127.0.0.1 devhost | sudo tee -a /etc/hosts
          when: on_fail
           steps:
             - run: echo "my step fails"
      

workflows:
  my_workflow:
    jobs:
      - my_job
